name: Testing

on:
  workflow_dispatch:

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build docker
        run: |
          DOCKER_BUILDKIT=1 docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
          DOCKER_BUILDKIT=1 docker buildx build --allow security.insecure -t test .
