name: Testing

on:
  workflow_dispatch:

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      # https://github.com/crazy-max/ghaction-docker-buildx/issues/172
      - name: Hack Docker FS to Build cryptography on armv6/armv7
        run: |
          df -h
          sudo swapon --show
          sudo dd if=/dev/zero of=/swapfile1 bs=1M count=8K 
          sudo chmod 600 /swapfile1
          sudo mkswap /swapfile1
          sudo swapon /swapfile1
          sudo swapon --show
          sudo free -h
          sudo systemctl stop docker
          sudo mount -t tmpfs -o size=7G tmpfs /var/lib/docker
          df -h
          sudo systemctl start docker

      - name: Set up qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build image
        run: |
          docker build -t test .
